{"name":"Cpp exception handling","group":"HackerRank - C++ - Debugging","url":"https://www.hackerrank.com/challenges/cpp-exception-handling/problem?isFullScreen=false&h_r=next-challenge&h_v=zen","interactive":false,"memoryLimit":512,"timeLimit":4000,"tests":[{"input":"0","output":"largest proper divisor is not defined for n=0\nreturning control flow to caller","id":1644306506115},{"id":1644306506091,"input":"9","output":"result=3\nreturning control flow to caller"}],"testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"CppExceptionHandling"}},"batch":{"id":"2f77e1b6-a04b-48ab-957e-cf65e9b7e8db","size":1},"srcPath":"c:\\Users\\rafis\\Desktop\\Problem\\Cpp_exception_handling.cpp"}